Format Locations file
APHA-CSU/btb-forestry pull request #10
Opened 2023-02-22 17:28 UTC by ellisrichardj

This PR is to add an additional process to format the locations file from the metadata warehouse for use by Augur.  Tab separated values are required, and the first column needs to identify the location type (e.g. CPH or County) - see below  It also adds County locations (from a separate static file) which will allow the display of County-level summaries on the map. 

CPH	01/006/0045	52.0153075045731	-0.414631106731372
CPH	01/012/0152	52.1140624236131	-0.609298037192273
CPH	01/045/0064	52.1872212958073	-0.333624906280236
CPH	01/045/0065	52.2119935594832	-0.356790325017313
CPH	01/075/0012	51.9265023941018	-0.622941104183655
County	Dyfed	52.089816	-4.095032
County	Gwent	51.744687	-2.902416
County	Powys	52.371127	-3.406622

2023-02-23 10:44 UTC, nick-pestell commented on bin/formatLocations.py
> +    Frames = [location_df, counties_df]
standard to use lowercase for variables/objects: with the capital F, this makes it look like a class. Same with the Allocations_df below. (I think that might be why github has made them a difference colour ...

2023-02-23 10:50 UTC, nick-pestell commented on bin/formatLocations.py
> +    AllLocations_df.to_csv('allLocations_{}.tsv'.format(date_out), sep='\t', header=None)
I think you could add `index=False` here and then remove line 18. :)

2023-02-23 10:52 UTC, nick-pestell requested changes
Looks good. Just two minor changes to the python file required I think.

2023-02-23 13:02 UTC, ellisrichardj commented on bin/formatLocations.py
> +    Frames = [location_df, counties_df]
Thanks - no changed

2023-02-23 13:03 UTC, ellisrichardj commented on bin/formatLocations.py
> +    AllLocations_df.to_csv('allLocations_{}.tsv'.format(date_out), sep='\t', header=None)
Good spot - makes sense

2023-02-23 13:36 UTC, nick-pestell approved these changes
Nice. Thanks for making those changes

2023-02-23 13:52 UTC, merged

2023-02-24 10:11 UTC, Hira-Naveed reviewed
Good to see the process taken to clean the data!