Prepare metadata for Nextstrain
APHA-CSU/btb-forestry pull request #3
Opened 2023-02-06 17:55 UTC by ellisrichardj

This PR makes use of the 'movement.csv' currently generated for `ViewBovine` to extract the appropriate metadata which will be required for building the `.json` files by `Augur` for display in in `Nextstrain`.  This is the first step towards automating the `Nextstrain` build.  `Pandas` has been used for csv manipulation and merging, particularly focussing on consistent use of the Submission number, whilst keeping the Sample number for matching to tree branch labels.  These processes can be updated once the format of data extracted from the metadata warehouse has been finalised.

2023-02-07 09:11 UTC, Hira-Naveed approved these changes
Richard, this is looking great and making sure we have the appropriate metadata in place for Nextstrain at this stage is super useful and this first step in automation of Nextstrain is a great milestone. I have also used the opportunity for reviewing this PR to learn some Pandas (thank you!).  And thank you for updating on next steps for when we have the MDWH side of things finalised.

2023-02-08 09:56 UTC, nick-pestell commented on main.nf
> +process metadata {
Would be nice to have a comment describing the process, as on line 30.

2023-02-08 09:56 UTC, nick-pestell commented on main.nf
> +process cladeMetadata{
Again, nice to have a comment above. As in line 30.

2023-02-08 09:57 UTC, nick-pestell commented on bin/cladeMetadata.py
> +    clademetadata_df = pd.merge(cladelist_df, sortedMetadata_df, on = 'Submission', how = 'left')
Quite pedantic, but in python keyword arguments, it's standard to have no space before and after the "=".

2023-02-08 09:59 UTC, nick-pestell commented on bin/cladeMetadata.py
> +    parser.add_argument('sortedMetadata_csv', help = 'path to sortedMetadata.csv')
So here as well, ideally there would be no space before and after "=".

2023-02-08 10:03 UTC, nick-pestell commented on bin/cladeMetadata.py
> +def combine(sortedMetadata_csv, cladelist_csv, clade):
A docstring would be nice here describing the function, in terms of arguments and return values.

2023-02-08 10:05 UTC, nick-pestell commented on bin/filterMetadata.py
> +    metadata_df['SampleName']=metadata_df['SampleName'].astype(object)
Here, there should be a space either side of the equals.

2023-02-08 10:22 UTC, nick-pestell commented on bin/filterMetadata.py
> +    metadata_df.drop_duplicates('SampleName', inplace = True)
I'm not sure what happens on lines 16-18, but I think maybe you're just keeping the first entry for each SampleName?
If that is what's happening, you could perhaps do it without sorting on SampleName first. 
e.g.
```
metadata_df.sort_values("MovementId", kind="mergesort", inplace=True)
metadata_df.drop_duplicates("SampleName", inplace=True)
```

2023-02-08 11:05 UTC, nick-pestell commented on bin/filterMetadata.py
> +    metadata_df.drop_duplicates('SampleName', inplace = True)
Oh sorry, you might also need `keep="first"` as an arg in `drop_duplicates`

2023-02-08 11:12 UTC, nick-pestell requested changes
Looks good, just a few things to change

2023-02-08 13:05 UTC, ellisrichardj commented
> Looks good, just a few things to change

Thanks - hopefully covered everything here

2023-02-09 10:04 UTC, nick-pestell approved these changes
Thanks for making those changes!

2023-02-09 10:08 UTC, merged